### ISSUE TITLE
Book Import/Export

### ISSUE THREAD

**Issue by FelixVicis** [johnRedden/TextbookProject#16]
We should have some form of functionality for book import/export.
### Tasks:
- [x] Design Book HTML Layout.
- [x] Export a book with this layout.
- [x] Create parser for layout
- [x] Import a book with this layout.
### Possible Issues:
- Reference ID's
  - We will end up scrubbing id's out of the exported book. They will not be valid with importing.
- Catalog to tie book to.
  - This may need to be selected again.
- Images
  - We may be forced to handle only image links, not actual images.
  - If you import a book that once had images in our system. you will have to replace all the images that were uploaded to us.

**Comment by FelixVicis** [comment]
## Update

We have a concept ready to parse an already exported book.
![image](https://cloud.githubusercontent.com/assets/6580094/15199194/3ec9856e-1791-11e6-86f2-8a9dbe0f8c2c.png)

I'm holding onto this as a FSM for my own sanity(_or what's left of it_). The important part is the forward edges. Back edges are allowed for everything except up to books; as we are only taking in one book at a time.

An example of this encoding in action is:

``` html

<!DOCTYPE html>
<html>
<body>

<div Book-Title>Book1</div>
<div Book-Version>1.234</div>
<div Book-Author>An Author</div>
<div Book-Tags>Hello;World;This;Is;Some;Tags</div>
<div Book-Description><p><strong>This could be a description for my book. But,&nbsp;<em>I dont think it is...</em></strong></p></div>

<div Chapter-Title>Chapter 2</div>
<div Chapter-Version>0</div>
<div Chapter-Description></div>

<div Section-Title>2.1 Section Title</div>
<div Section-Version>0</div>
<div Section-Description></div>

<div Objective-Title>2.1.2 Objective 2</div>
<div Objective-Version>0</div>
<div Objective-Author></div>
<div Objective-Content></div>
<div Objective-KeyTakeaways></div>

<div Objective-Title>2.1.1 Objective</div>
<div Objective-Version>0</div>
<div Objective-Author></div>
<div Objective-Content></div>
<div Objective-KeyTakeaways></div>

<div Section-Title>2.2 Section 2 Title</div>
<div Section-Version>0</div>
<div Section-Description></div>

<div Objective-Title>2.2.1</div>
<div Objective-Version>0</div>
<div Objective-Author></div>
<div Objective-Content></div>
<div Objective-KeyTakeaways></div>

<div Exercise-Instruction>Say Goodbye</div>
<div Exercise-Question></div>
<div Exercise-Solution></div>

<div Exercise-Instruction>Say Hello!</div>
<div Exercise-Question></div>
<div Exercise-Solution></div>

</body>
</html>
```

**Comment by FelixVicis** [comment]
## Update

### Parser Rules:
- Ignore Blank/Invalid-Prefix lines.
- DOM Blocks should never extend past 1 level unless parameter value takes in HTML
- If any required(non-if) statement below fails, due to EOF or parse error: exit.

``` TEXT
10. MUST Line-Prefix is: `<i book`
11. Create New Book
12. IF Line-Prefix is:
        `<div book-title`
        `<div book-version`
        `<div book-author`
        `<div book-tags`
        `<div book-description`
    THEN 
        Book.Parameter = TEXT/HTML
        GOTO 12
    ELSE 
        Push Book
20. MUST Line-Prefix is `<i chapter`
21. Create New Chapter
22. IF Line-Prefix is: 
        `<div chapter-title`
        `<div chapter-version`
        `<div chapter-description`
    THEN
        Chapter.Parameter = TEXT/HTML
        GOTO 22
    ELSE
        Push Chapter
30. IF Line-Prefix is `<i chapter`
    GOTO 21
40. MUST Line-Prefix is `<i section`
41. Create New Section
42. IF Line-Prefix is:
        <div section-title
        <div section-version
        <div section-description
    THEN
        Section.Parameter = TEXT/HTML
        GOTO 42
    ElSE
        Push Section
50. IF Line-Prefix is `<i chapter`
    GOTO 21
51. IF Line-Prefix is `<i section`
    GOTO 41
60. MUST Line-Prefix is `<i objective`
61. Create New Objective
62. IF Line-Prefix is:
        <div objective-title
        <div objective-version
        <div objective-author
        <div objective-content
        <div objective-keytakeaways
    THEN
        Objective.Parameter = TEXT/HTML
        GOTO 62
    ELSE
        Push Objective
70. IF Line-Prefix is `<i chapter`
    GOTO 21
71. IF Line-Prefix is `<i section`
    GOTO 41
72. IF Line-Prefix is `<i objective`
    GOTO 61
80. MUST Line-Prefix is `<i exercise`
81. Create New Exercise
82. If Line-Prefix is:
        <div exercise-instruction
        <div exercise-question
        <div exercise-solution
    THEN
        Exercise.Parameter = TEXT/HTML
        GOTO 82
    ELSE
        Push Exercise
90. IF Line-Prefix is `<i chapter`
    GOTO 21
91. IF Line-Prefix is `<i section`
    GOTO 41
92. IF Line-Prefix is `<i objective`
    GOTO 61
93. IF Line-Prefix is `<i exercise`
    GOTO 81
```

### Export Layout

Book: 

```
<i book=""></i>
<div book-title="">TEXT</div>
<div book-version="">FLOAT</div>
<div book-author="">TEXT</div>
<div book-tags="">TEXT</div>
<div book-description="">HTML</div>  
```

Chapter:

```
<i chapter=""></i>
<div chapter-title="">TEXT</div>
<div chapter-version="">FLOAT</div>
<div chapter-description="">HTML</div>
```

Section:

```
<i section=""></i>
<div section-title="">TEXT</div>
<div section-version="">FLOAT</div>
<div section-description="">HTML</div>
```

Objective:

```
<i objective=""></i>
<div objective-title="">TEXT</div>
<div objective-version="">FLOAT</div>
<div objective-author="">TEXT</div>
<div objective-content="">HTML</div>
<div objective-keytakeaways="">HTML</div>
```

Exercise:

```
<i exercise=""></i>
<div exercise-instruction="">TEXT</div>
<div exercise-question="">HTML</div>
<div exercise-solution="">HTML</div>
```

**Comment by FelixVicis** [comment]
### Update

The structure above is working well. We now have a regex to cut out all info from an incoming file that does not pass. Can now break incoming lines into Key:Value pairs. State Machine's next.

**Comment by FelixVicis** [comment]
### Update

Working FSM example. It does not yet actually preform actions but it will describe the actions that should be taken. The regex has been made a fair bit smarter too, knowing that it should select on only our special tags.

The regex in action: https://regex101.com/r/hY2nK8/2
